set nocompatible
filetype off

set tags=ctags

call plug#begin('~/.vim/plugged')

Plug 'bluz71/vim-moonfly-colors'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-surround'
Plug 'thoughtbot/vim-rspec'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'preservim/nerdtree'
Plug 'christoomey/vim-tmux-navigator'
Plug 'christoomey/vim-tmux-runner'
Plug 'neoclide/coc.nvim', { 'branch': 'master', 'do': 'yarn install --frozen-lockfile' }
Plug 'morhetz/gruvbox'
Plug 'dikiaap/minimalist'
Plug 'sheerun/vim-polyglot'

call plug#end()

set relativenumber
set nowrap
set smarttab
set cindent
set tabstop=2
set shiftwidth=2
set termguicolors

colorscheme gruvbox
filetype plugin indent on

let mapleader = "\<Space>"

nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>
noremap ss :w<cr>


imap jk <esc>
imap kj <esc>

let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching = 0

autocmd VimResized * :wincmd =

nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
nnoremap <leader>= :wincmd =<cr>

map <leader>va :VtrAttachToPane<cr>
map <leader>sc :VtrSendCommandToRunner<cr>
map <leader>sf :VtrSendFile<cr>
map <leader>sl :VtrSendLinesToRunner<cr>
map <leader>or :VtrOpenRunner<cr>
map <leader>kr :VtrKillRunner<cr>
map <leader>fr :VtrFocusRunner<cr>
map <leader>dr :VtrDetachRunner<cr>
map <leader>cr :VtrClearRunner<cr>
map <leader>fr :VtrFlushRunner<cr>


map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

let g:VtrUseVtrMaps = 1
nnoremap <leader>irb :VtrOpenRunner {'orientation': 'h', 'percentage': 50, 'cmd': 'irb'}<cr>
nnoremap <leader>osr :VtrOpenRunner {'orientation': 'h', 'percentage': 50}<cr>

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

inoremap <silent><expr> <c-space> coc#refresh()
map <C-n> :NERDTreeToggle<CR>
